version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/java"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/web/vtadmin"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/docker/binaries/*"
      - "/docker/bootstrap"
      - "/docker/lite"
      - "/docker/mini"
      - "/docker/vttestserver"
      - "/examples/compose/external_db/mysql"
      - "/go/mysql/collations/tools/colldump"
    schedule:
      interval: "weekly"
