apiVersion: v1
name: vitess
version: 1.0.1
description: Single-Chart Vitess Cluster
keywords:
  - vitess
  - mysql
  - maria
  - mariadb
  - percona
  - sql
  - database
  - shard
home: http://vitess.io
sources:
  - https://github.com/vitessio/vitess
maintainers:
  - name: Vitess Project
    email: vitess@googlegroups.com
icon: http://vitess.io/images/vitess_logo_with_border.svg
