topology:
  deploymentType: test
  cells:
    - name: "zone1"
      vtctld:
        replicas: 1
      vtgate:
        replicas: 1
      mysqlProtocol:
        enabled: true
        authType: "none"
      keyspaces:
        - name: "commerce"
          shards:
            - name: "0"
              tablets:
                - type: "replica"
                  vttablet:
                    replicas: 3
          schema:
            initial: |-
              create table product(
                sku varbinary(128),
                description varbinary(128),
                price bigint,
                primary key(sku)
              );
              create table customer(
                customer_id bigint not null auto_increment,
                email varbinary(128),
                primary key(customer_id)
              );
              create table corder(
                order_id bigint not null auto_increment,
                customer_id bigint,
                sku varbinary(128),
                price bigint,
                primary key(order_id)
              );
          vschema:
            initial: |-
              {
                "tables": {
                  "product": {},
                  "customer": {},
                  "corder": {}
                }
              }

vttablet:
  # It's generally not recommended to override this value for production usage.
  terminationGracePeriodSeconds: 1

pmm:
  enabled: false

orchestrator:
  enabled: false
