topology:
  deploymentType: test
  cells:
    - name: "zone1"
      vtctld:
        replicas: 1
      vtgate:
        replicas: 1
      mysqlProtocol:
        enabled: true
        authType: "none"
      keyspaces:
        - name: "commerce"
          shards:
            - name: "0"
              tablets:
                - type: "replica"
                  vttablet:
                    replicas: 3
        - name: "customer"
          shards:
            - name: "0"
              tablets:
                - type: "replica"
                  vttablet:
                    replicas: 3

jobs:
  - name: "move-tables"
    kind: "vtctlclient"
    command: "MoveTables -workflow=commerce2customer commerce customer \'{\"customer\":{}, \"corder\":{}}\'"

vttablet:
  # It's generally not recommended to override this value for production usage.
  terminationGracePeriodSeconds: 1

pmm:
  enabled: false

orchestrator:
  enabled: false
