version: '2.1'

volumes:
  vol-db:

services:
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-pass}
      MYSQL_DATABASE: ${MYSQL_DB:-commerce}
      MYSQL_USER: ${MYSQL_USER:-dbuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dbpass}
    volumes:
      - vol-db:/var/lib/mysql
      - ./mysql/:/docker-entrypoint-initdb.d/
      - ./mysql/master_mysql57.cnf:/etc/mysql/conf.d/master_mysql57.cnf:ro
      - ./mysql/log:/var/log/mysql
    command:
      - --server-id=1
      - --log-bin=mysql-bin
      - --gtid_mode=ON
      - --enforce_gtid_consistency
      - --general_log=1
      - --slow_query_log=1
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$${MYSQL_ROOT_PASSWORD} --execute \"SHOW DATABASES;\""
      timeout: 10s
      retries: 10
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: rmsoft
    ports:
      - "8081:8080"
