topology:
  cells:
    - name: "zone1"
      etcd:
        replicas: 1
      vtctld:
        replicas: 1
      vtgate:
        replicas: 1
      mysqlProtocol:
        enabled: true
        authType: "none"
      keyspaces:
        - name: "commerce"
          shards:
            - name: "0"
              tablets:
                - type: "replica"
                  vttablet:
                    replicas: 2
                - type: "rdonly"
                  vttablet:
                    replicas: 1
          schema:
            postsplit: |-
              drop table customer;
              drop table corder;
          vschema:
            phase1: |-
              {
                "tables": {
                  "product": {}
                }
              }
        - name: "customer"
          shards:
            - name: "0"
              tablets:
                - type: "replica"
                  vttablet:
                    replicas: 2
                - type: "rdonly"
                  vttablet:
                    replicas: 1

jobs:
  - name: "vclean1"
    kind: "vtctlclient"
    command: "SetShardTabletControl -blacklisted_tables=customer,corder -remove commerce/0 rdonly"
  - name: "vclean2"
    kind: "vtctlclient"
    command: "SetShardTabletControl -blacklisted_tables=customer,corder -remove commerce/0 replica"
  - name: "vclean3"
    kind: "vtctlclient"
    command: "SetShardTabletControl -blacklisted_tables=customer,corder -remove commerce/0 master"

etcd:
  replicas: 1
  resources:

vtctld:
  serviceType: "NodePort"
  resources:

vtgate:
  serviceType: "NodePort"
  resources:

vttablet:
  resources:
  mysqlResources:

vtworker:
  resources:

pmm:
  enabled: false

orchestrator:
  enabled: false
