name: Assign Milestone

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  build:
    name: Assign Milestone
    runs-on: ubuntu-22.04

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.2

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current version of Vitess
        run: |
          echo "vitess_version=$(go run ./go/tools/version/version.go)" >> $GITHUB_ENV
          
      - name: set milestone
        uses: zoispag/action-assign-milestone@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          milestone: v${{ env.vitess_version }}