name: Auto Approval of Bot Pull Requests
on:
  pull_request:
    types: [opened, reopened]

permissions:
  contents: read

jobs:
  auto_approve:
    name: Auto Approve Pull Request
    runs-on: ubuntu-24.04

    permissions:
      pull-requests: write  # only given on local PRs, forks run with `read` access

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: 'false'

      - name: Auto Approve Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # here we are checking that the PR has been created by the vitess-bot[bot] account and that it is not a draft
          # if there is a merge conflict in the backport, the PR will always be created as a draft, meaning we can rely
          # on checking whether or not the PR is a draft
          if [[ "${{github.event.pull_request.user.login}}" ==  "vitess-bot[bot]" ]] && [[ "${{github.event.pull_request.draft}}" == "false" ]]; then
            gh pr review ${{ github.event.pull_request.number }} --approve
          fi
