name: check_make_vtadmin_authz_testgen
on: [push, pull_request]
jobs:

  build:
    name: Check Make vtadmin_authz_testgen
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Check for changes in relevant files
      uses: frouioui/paths-filter@main
      id: changes
      with:
        token: ''
        filters: |
          vtadmin_changes:
            - 'bootstrap.sh'
            - 'tools/**'
            - 'build.env'
            - 'go.[sumod]'
            - 'Makefile'
            - 'go/vt/vtadmin/**'

    - name: Set up Go
      uses: actions/setup-go@v2
      if: steps.changes.outputs.vtadmin_changes == 'true'
      with:
        go-version: 1.18.4

    - name: Tune the OS
      if: steps.changes.outputs.vtadmin_changes == 'true'
      run: |
        echo '1024 65535' | sudo tee -a /proc/sys/net/ipv4/ip_local_port_range


    - name: Get dependencies
      if: steps.changes.outputs.vtadmin_changes == 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y make unzip g++ etcd curl git wget
        sudo service etcd stop
        go mod download
        go install golang.org/x/tools/cmd/goimports@latest

    - name: Run make minimaltools
      if: steps.changes.outputs.vtadmin_changes == 'true'
      run: |
        make minimaltools

    - name: check_make_vtadmin_authz_testgen
      if: steps.changes.outputs.vtadmin_changes == 'true'
      run: |
        tools/check_make_vtadmin_authz_testgen.sh
