name: check_make_vtadmin_authz_testgen
on: [push, pull_request]
jobs:

  build:
    name: Check Make vtadmin_authz_testgen
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/slackhq/vitess-addons
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
    - name: Check if workflow needs to be skipped
      id: skip-workflow
      run: |
        skip='false'
        echo Skip ${skip}
        echo "skip-workflow=${skip}" >> $GITHUB_OUTPUT

    - name: Check out code
      if: steps.skip-workflow.outputs.skip-workflow == 'false'
      uses: actions/checkout@v3

    - name: Check for changes in relevant files
      if: steps.skip-workflow.outputs.skip-workflow == 'false'
      uses: frouioui/paths-filter@main
      id: changes
      with:
        token: ''
        filters: |
          vtadmin_changes:
            - 'bootstrap.sh'
            - 'tools/**'
            - 'build.env'
            - 'go.sum'
            - 'go.mod'
            - 'Makefile'
            - 'go/vt/vtadmin/**'
            - '.github/workflows/check_make_vtadmin_authz_testgen.yml'

    - name: Set up Go
      uses: actions/setup-go@v3
      if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.vtadmin_changes == 'true'
      with:
        go-version: 1.21.10

    - name: Setup github.com/slackhq/vitess-additions access token
      run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/

    - name: Tune the OS
      if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.vtadmin_changes == 'true'
      run: |
        echo '1024 65535' | sudo tee -a /proc/sys/net/ipv4/ip_local_port_range


    - name: Get dependencies
      if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.vtadmin_changes == 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y make unzip g++ etcd curl git wget
        sudo service etcd stop
        go mod download
        go install golang.org/x/tools/cmd/goimports@latest

    - name: Run make minimaltools
      if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.vtadmin_changes == 'true'
      run: |
        make minimaltools

    - name: check_make_vtadmin_authz_testgen
      if: steps.skip-workflow.outputs.skip-workflow == 'false' && steps.changes.outputs.vtadmin_changes == 'true'
      run: |
        tools/check_make_vtadmin_authz_testgen.sh
