name: check_make_sizegen
on: [push, pull_request]
jobs:

  build:
    name: Check Make Sizegen
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Check for changes in relevant files
      uses: dorny/paths-filter@v2
      id: changes
      with:
        token: ${{ github.token }}
        filters: |
          sizegen:
            - 'go/**/*.go'
            - 'test.go'
            - 'Makefile'
            - 'build.env'
            - 'go.[sumod]'
            - 'tools/**'
            - 'bootstrap.sh'

    - name: Set up Go
      if: steps.changes.outputs.sizegen == 'true'
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.1

    - name: Tune the OS
      if: steps.changes.outputs.sizegen == 'true'
      run: |
        echo '1024 65535' | sudo tee -a /proc/sys/net/ipv4/ip_local_port_range

    - name: Get dependencies
      if: steps.changes.outputs.sizegen == 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y make unzip g++ etcd curl git wget
        sudo service etcd stop
        go mod download
        go install golang.org/x/tools/cmd/goimports@latest

    - name: Run make minimaltools
      if: steps.changes.outputs.sizegen == 'true'
      run: |
        make minimaltools

    - name: check_make_sizegen
      if: steps.changes.outputs.sizegen == 'true'
      run: |
        tools/check_make_sizegen.sh
