name: check_make_visitor
on: [push, pull_request]
jobs:

  build:
    name: Check Make Visitor
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Check for changes in relevant files
      uses: dorny/paths-filter@v2
      id: changes
      with:
        token: ${{ github.token }}
        filters: |
          visitor:
            - 'go/tools/asthelpergen/**'
            - 'go/vt/sqlparser/**'
            - 'Makefile'
            - 'build.env'
            - 'go.[sumod]'
            - 'tools/**'
            - 'bootstrap.sh'
            - 'misc/git/hooks/asthelpers'

    - name: Set up Go
      if: steps.changes.outputs.visitor == 'true'
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.1

    - name: Tune the OS
      if: steps.changes.outputs.visitor == 'true'
      run: |
        echo '1024 65535' | sudo tee -a /proc/sys/net/ipv4/ip_local_port_range

    - name: Get dependencies
      if: steps.changes.outputs.visitor == 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y make unzip g++ etcd curl git wget
        sudo service etcd stop
        go mod download
        go install golang.org/x/tools/cmd/goimports@latest

    - name: Run make minimaltools
      if: steps.changes.outputs.visitor == 'true'
      run: |
        make minimaltools

    - name: check_make_visitor
      if: steps.changes.outputs.visitor == 'true'
      run: |
        misc/git/hooks/asthelpers
