name: check_make_vtadmin_web_proto
on: [push, pull_request]
jobs:

  build:
    name: Check Make VTAdmin Web Proto
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Check for changes in relevant files
      uses: frouioui/paths-filter@main
      id: changes
      with:
        token: ''
        filters: |
          proto_changes:
            - 'bootstrap.sh'
            - 'tools/**'
            - 'build.env'
            - 'go.[sumod]'
            - 'Makefile'
            - 'go/vt/proto/**'
            - 'proto/*.proto'
            - 'web/vtadmin/src/proto/**'

    - name: Set up Go
      uses: actions/setup-go@v2
      if: steps.changes.outputs.proto_changes == 'true'
      with:
        go-version: 1.18.4

    - name: Setup Node
      if: steps.changes.outputs.proto_changes == 'true'
      uses: actions/setup-node@v2
      with:
        # node-version should match package.json
        node-version: '16.13.0'

    - name: Install npm dependencies
      if: steps.changes.outputs.proto_changes == 'true'
      run: npm ci
      working-directory: ./web/vtadmin

    - name: check_make_vtadmin_web_proto
      if: steps.changes.outputs.proto_changes == 'true'
      run: |
        tools/check_make_vtadmin_web_proto.sh
