name: close_stale_pull_requests
on:
  schedule:
    - cron: '0 1 * * *'

  workflow_dispatch: {}

permissions: read-all

jobs:
  close_stale_pull_requests:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/stale@997185467fa4f803885201cee163a9f38240193d # v10.1.1
        with:
          days-before-stale: 30
          # Do not handle issues at all. We only want to handle PRs.
          days-before-issue-stale: -1

          stale-pr-message: |
            This PR is being marked as stale because it has been open for 30 days with no activity. To rectify, you may do any of the following:

            - Push additional commits to the associated branch.
            - Remove the stale label.
            - Add a comment indicating why it is not stale.

            If no action is taken within 7 days, this PR will be closed.
          close-pr-message: "This PR was closed because it has been stale for 7 days with no activity."

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

