name: docker_ci
on:
  push:
    branches:
      - "main"
      - "release-[0-9]+.[0-9]"
    tags: "**"
  pull_request:
    branches: "**"
permissions: read-all

env:
  BOOTSTRAP_VERSION: "ci"
  BOOTSTRAP_FLAVOR: "mysql80"

jobs:
  build:
    name: Docker Test (${{ matrix.shard }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        shard: [java, docker_cluster]

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit

      - name: Skip CI
        run: |
          if [[ "${{contains( github.event.pull_request.labels.*.name, 'Skip CI')}}" == "true" ]]; then
            echo "skipping CI due to the 'Skip CI' label"
            exit 1
          fi

      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: "false"

      - name: Check for changes in relevant files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          token: ""
          filters: |
            end_to_end:
              - 'test/config.json'
              - 'go/**/*.go'
              - 'test.go'
              - 'Makefile'
              - 'build.env'
              - 'go.sum'
              - 'go.mod'
              - 'proto/*.proto'
              - 'tools/**'
              - 'config/**'
              - 'bootstrap.sh'
              - 'docker/**'
              - 'java/**'
              - '.github/workflows/docker_ci.yml'

      - name: Set up Docker Buildx
        if: steps.changes.outputs.end_to_end == 'true'
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Build bootstrap common image
        if: steps.changes.outputs.end_to_end == 'true'
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: docker/bootstrap/Dockerfile.common
          push: false
          load: true
          tags: vitess/bootstrap:${{ env.BOOTSTRAP_VERSION }}-common
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build bootstrap flavor image
        if: steps.changes.outputs.end_to_end == 'true'
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: docker/bootstrap/Dockerfile.${{ env.BOOTSTRAP_FLAVOR }}
          push: false
          load: true
          tags: vitess/bootstrap:${{ env.BOOTSTRAP_VERSION }}-${{ env.BOOTSTRAP_FLAVOR }}
          build-args: |
            bootstrap_version=${{ env.BOOTSTRAP_VERSION }}
            image=vitess/bootstrap:${{ env.BOOTSTRAP_VERSION }}-common
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set up Go
        if: steps.changes.outputs.end_to_end == 'true'
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod

      - name: Tune the OS
        if: steps.changes.outputs.end_to_end == 'true'
        uses: ./.github/actions/tune-os

      - name: Run docker tests - ${{ matrix.shard }}
        if: steps.changes.outputs.end_to_end == 'true'
        run: |
          go run test.go -docker=true -pull=false -flavor=${{ env.BOOTSTRAP_FLAVOR }} -bootstrap-version=${{ env.BOOTSTRAP_VERSION }} --follow -shard ${{ matrix.shard }}
