name: Update Golang Dependencies

on:
  schedule:
    - cron: "0 0 1,15 * *" # Runs every month on the 1st and 15th days at midnight UTC
  workflow_dispatch:

permissions: read-all

jobs:
  update_golang_deps:
    if: github.repository == 'vitessio/vitess'
    permissions:
      contents: write
      pull-requests: write
    name: Update Golang Dependencies
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: main
          persist-credentials: 'false'

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod

      - name: Upgrade the Golang Dependencies
        id: detect-and-update
        run: |
          go get -u ./...

          output=$(git status -s)
          if [ -z "${output}" ]; then
            exit 0
          fi

          go mod tidy

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.CREATE_PR_VITESS_BOT }}
          branch: "upgrade-go-deps-on-main"
          commit-message: "upgrade go deps"
          signoff: true
          delete-branch: true
          team-reviewers: Release
          title: "Upgrade the Golang Dependencies"
          body: |
            This Pull Request updates all the Golang dependencies to their latest version using `go get -u ./...`.
            
            cc @vitessio/release
          base: main
          labels: |
            go
            Component: General
            Type: Dependencies
