name: Reparent New VTTablet - Upgrade Downgrade Testing
on:
  push:
    branches:
      - "main"
      - "release-[0-9]+.[0-9]"
    tags: '**'
  pull_request:
    branches: '**'

concurrency:
  group: format('{0}-{1}', ${{ github.ref }}, 'Upgrade Downgrade Testing Reparent New VTTablet')
  cancel-in-progress: true

permissions: read-all

# This test ensures that our end-to-end tests work using Vitess components
# (vtctl, vttablet, etc) built on different versions.

jobs:

  upgrade_downgrade_test:
    timeout-minutes: 60
    name: Run Upgrade Downgrade Test - Reparent New VTTablet
    runs-on: oracle-vm-16cpu-64gb-x86-64

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
      with:
        egress-policy: audit

    - name: Skip CI
      run: |
        if [[ "${{contains( github.event.pull_request.labels.*.name, 'Skip CI')}}" == "true" ]]; then
          echo "skipping CI due to the 'Skip CI' label"
          exit 1
        fi

    - name: Check out commit's code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        fetch-depth: 0
        persist-credentials: 'false'

    - name: Set output with latest release branch
      id: output-next-release-ref
      run: |
        next_release_ref=$(./tools/get_next_release.sh ${{github.base_ref}} ${{github.ref}})
        echo $next_release_ref
        echo "next_release_ref=${next_release_ref}" >> $GITHUB_OUTPUT

    - name: Check for changes in relevant files
      if: steps.output-next-release-ref.outputs.next_release_ref != ''
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      id: changes
      with:
        token: ''
        filters: |
          end_to_end:
            - 'test/config.json'
            - 'go/**'
            - 'go/**/*.go'
            - 'test.go'
            - 'Makefile'
            - 'build.env'
            - 'go.sum'
            - 'go.mod'
            - 'proto/*.proto'
            - 'tools/**'
            - 'config/**'
            - 'bootstrap.sh'
            - '.github/workflows/upgrade_downgrade_test_reparent_new_vttablet.yml'

    - name: Tune the OS
      if: steps.output-next-release-ref.outputs.next_release_ref != '' && steps.changes.outputs.end_to_end == 'true'
      uses: ./.github/actions/tune-os

    - name: Set up python
      if: steps.output-next-release-ref.outputs.next_release_ref != '' && steps.changes.outputs.end_to_end == 'true'
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0

    - name: Setup MySQL
      if: steps.output-next-release-ref.outputs.next_release_ref != '' && steps.changes.outputs.end_to_end == 'true'
      uses: ./.github/actions/setup-mysql
      with:
        flavor: mysql-8.4

    - name: Get base dependencies
      timeout-minutes: 10
      if: steps.output-next-release-ref.outputs.next_release_ref != '' && steps.changes.outputs.end_to_end == 'true'
      run: |
        sudo DEBIAN_FRONTEND="noninteractive" apt-get update

        # Install everything else we need, and configure
        sudo apt-get install -y make unzip g++ etcd-client etcd-server curl git wget
        
        sudo service etcd stop

        wget https://repo.percona.com/apt/percona-release_latest.$(lsb_release -sc)_all.deb
        sudo apt-get install -y gnupg2
        sudo dpkg -i percona-release_latest.$(lsb_release -sc)_all.deb
        sudo percona-release enable-only tools
        sudo apt-get update
        sudo apt-get install -y percona-xtrabackup-80

    # Checkout to the next release of Vitess
    - name: Check out other version's code (${{ steps.output-next-release-ref.outputs.next_release_ref }})
      if: steps.output-next-release-ref.outputs.next_release_ref != '' && steps.changes.outputs.end_to_end == 'true'
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        ref: ${{ steps.output-next-release-ref.outputs.next_release_ref }}
        persist-credentials: 'false'

    - name: Set up Go
      if: steps.output-next-release-ref.outputs.next_release_ref != '' && steps.changes.outputs.end_to_end == 'true'
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version-file: go.mod
        cache: false

    - name: Get dependencies for the next release
      if: steps.output-next-release-ref.outputs.next_release_ref != '' && steps.changes.outputs.end_to_end == 'true'
      run: |
        go mod download

    - name: Building next release's binaries
      if: steps.output-next-release-ref.outputs.next_release_ref != '' && steps.changes.outputs.end_to_end == 'true'
      timeout-minutes: 10
      run: |
        source build.env
        NOVTADMINBUILD=1 make build
        mkdir -p /tmp/vitess-build-other/
        cp -R bin /tmp/vitess-build-other/
        rm -Rf bin/*

    # Checkout to this build's commit
    - name: Check out commit's code
      if: steps.output-next-release-ref.outputs.next_release_ref != '' && steps.changes.outputs.end_to_end == 'true'
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        persist-credentials: 'false'

    - name: Set up Go
      if: steps.output-next-release-ref.outputs.next_release_ref != '' && steps.changes.outputs.end_to_end == 'true'
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version-file: go.mod
        cache: false

    - name: Get dependencies for this commit
      if: steps.output-next-release-ref.outputs.next_release_ref != '' && steps.changes.outputs.end_to_end == 'true'
      run: |
        go mod download

    - name: Building the binaries for this commit
      if: steps.output-next-release-ref.outputs.next_release_ref != '' && steps.changes.outputs.end_to_end == 'true'
      timeout-minutes: 10
      run: |
        source build.env
        NOVTADMINBUILD=1 make build
        mkdir -p /tmp/vitess-build-current/
        cp -R bin /tmp/vitess-build-current/

    # Swap the binaries. Use vtctl version n and keep vttablet at version n+1
    - name: Use current version Vtctl, and other version VTTablet
      if: steps.output-next-release-ref.outputs.next_release_ref != '' && steps.changes.outputs.end_to_end == 'true'
      run: |
        source build.env

        rm -f $PWD/bin/vttablet $PWD/bin/mysqlctl $PWD/bin/mysqlctld
        cp /tmp/vitess-build-other/bin/vttablet $PWD/bin/vttablet
        cp /tmp/vitess-build-other/bin/mysqlctl $PWD/bin/mysqlctl
        cp /tmp/vitess-build-other/bin/mysqlctld $PWD/bin/mysqlctld
        vtctl --version
        vttablet --version

    # Running a test with vtctl at version n and vttablet at version n+1
    - name: Run reparent tests (vtctl=N, vttablet=N+1)
      if: steps.output-next-release-ref.outputs.next_release_ref != '' && steps.changes.outputs.end_to_end == 'true'
      run: |
        rm -rf /tmp/vtdataroot
        mkdir -p /tmp/vtdataroot

        source build.env
        go run test.go -skip-build -keep-data=false -docker=false -print-log -follow -tag upgrade_downgrade_reparent
