name: vtadmin-web build

# In specifying the 'paths' property, we need to include the path to this workflow .yml file. 
# See https://github.community/t/trigger-a-workflow-on-change-to-the-yml-file-itself/17792/4)
on:
  push:
    branches:
      - "main"
      - "release-[0-9]+.[0-9]"
    tags: '**'
    paths:
      - '.github/workflows/vtadmin_web_build.yml'
      - 'web/vtadmin/**'
  pull_request:
    branches: '**'
    paths:
      - '.github/workflows/vtadmin_web_build.yml'
      - 'web/vtadmin/**'

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Skip CI
        run: |
          if [[ "${{contains( github.event.pull_request.labels.*.name, 'Skip CI')}}" == "true" ]]; then
            echo "skipping CI due to the 'Skip CI' label"
            exit 1
          fi

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: 'false'

      - name: Tune the OS
        uses: ./.github/actions/tune-os

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          # node-version should match package.json
          node-version: '22.13.1'

      - name: Install dependencies
        run: cd ./web/vtadmin && npm ci

      - name: Build front-end
        run: cd ./web/vtadmin && npm run build

    # Cancel pending and in-progress runs of this workflow if a newer ref is pushed to CI.
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
