name: vtadmin-web build

# In specifying the 'paths' property, we need to include the path to this workflow .yml file. 
# See https://github.community/t/trigger-a-workflow-on-change-to-the-yml-file-itself/17792/4)
on:
  push:
    paths:
      - '.github/workflows/vtadmin_web_build.yml'
      - 'web/vtadmin/**'
  pull_request:
    paths:
      - '.github/workflows/vtadmin_web_build.yml'
      - 'web/vtadmin/**'

defaults:
  run:
    working-directory: ./web/vtadmin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          # node-version should match package.json
          node-version: '14.15'

      - name: Install dependencies
        run: npm install

      - name: Build front-end
        run: npm run build
