apiVersion: v1beta1
kind: Pod
id: vtctld
desiredState:
  manifest:
    version: v1beta1
    id: vtctld
    containers:
      - name: vtctld
        image: vitess/root
        volumeMounts:
          - name: syslog
            mountPath: /dev/log
          - name: vtdataroot
            mountPath: /vt/vtdataroot
        command:
          - sh
          - "-c"
          - >-
            mkdir -p $VTDATAROOT/tmp &&
            chown -R vitess /vt &&
            su -p -c "/vt/bin/vtctld -debug -templates $VTTOP/go/cmd/vtctld/templates -log_dir $VTDATAROOT/tmp -port 15000 -topo_implementation etcd -etcd_global_addrs http://$ETCD_GLOBAL_SERVICE_HOST:$ETCD_GLOBAL_SERVICE_PORT" vitess
    volumes:
      - name: syslog
        source: {hostDir: {path: /dev/log}}
      - name: vtdataroot
        source: {emptyDir: {}}
labels:
  name: vtctld
