kind: ReplicationController
apiVersion: v1
metadata:
  name: vtgate-{{cell}}
spec:
  replicas: {{replicas}}
  template:
    metadata:
      labels:
        component: vtgate
        cell: {{cell}}
        app: vitess
    spec:
      containers:
        - name: vtgate
          image: vitess/root
          livenessProbe:
            httpGet:
              path: /debug/vars
              port: 15001
            initialDelaySeconds: 30
            timeoutSeconds: 5
          volumeMounts:
            - name: syslog
              mountPath: /dev/log
            - name: vtdataroot
              mountPath: /vt/vtdataroot
          resources:
            limits:
              memory: "4Gi"
              cpu: "6"
          command:
            - sh
            - "-c"
            - >-
              mkdir -p $VTDATAROOT/tmp &&
              chown -R vitess /vt &&
              su -p -c "/vt/bin/vtgate
              -topo_implementation etcd
              -etcd_global_addrs http://etcd-global:4001
              -log_dir $VTDATAROOT/tmp
              -alsologtostderr
              -port 15001
              -grpc_port 15991
              -tablet_protocol grpc
              -service_map 'bsonrpc-vt-vtgateservice,grpc-vtgateservice'
              -cell {{cell}}" vitess
          env:
            - name: GOMAXPROCS
              value: "16"
      volumes:
        - name: syslog
          hostPath: {path: /dev/log}
        - name: vtdataroot
          {{vtdataroot_volume}}
