kind: ReplicationController
apiVersion: v1
metadata:
  name: vtgate-{{cell}}
spec:
  replicas: {{replicas}}
  template:
    metadata:
      labels:
        component: vtgate
        cell: {{cell}}
        app: vitess
    spec:
      containers:
        - name: vtgate
          image: {{vitess_image}}
          livenessProbe:
            httpGet:
              path: /debug/vars
              port: 15001
            initialDelaySeconds: 30
            timeoutSeconds: 5
          volumeMounts:
            - name: syslog
              mountPath: /dev/log
            - name: vtdataroot
              mountPath: /vt/vtdataroot
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          command:
            - sh
            - "-c"
            - >-
              mkdir -p $VTDATAROOT/tmp &&
              chown -R vitess /vt &&
              su -p -c "/vt/bin/vtgate
              -topo_implementation etcd2
              -topo_global_server_address http://etcd-global-client:2379
              -topo_global_root /global
              -log_dir $VTDATAROOT/tmp
              -alsologtostderr
              -port 15001
              -grpc_port 15991
              -mysql_server_port {{mysql_server_port}}
              -mysql_auth_server_static_string '{\"mysql_user\":{\"Password\":\"mysql_password\"}}'
              -service_map 'grpc-vtgateservice'
              -cells_to_watch {{cell}}
              -tablet_types_to_wait MASTER,REPLICA
              -gateway_implementation discoverygateway
              -cell {{cell}}" vitess
      volumes:
        - name: syslog
          hostPath: {path: /dev/log}
        - name: vtdataroot
          emptyDir: {}

